### ISSUE TITLE
Manually embed the chat room on the website

### ISSUE THREAD

**Issue by boontdustie** [HollowEarthRadio/lpfm-website#67]

**Comment by btpnlsl** [comment]
@boontdustie - Can you point me at the JS code for this?

**Comment by boontdustie** [comment]
http://www.hollowearthradio.org/admin/events/3/edit

**Comment by boontdustie** [comment]
Here is the chatroom if you want to change stuff: 

http://her-fm.chatango.com/clonegroup#

**Comment by btpnlsl** [comment]
Done. Reopen this one if there are any changes to be made in things like size/color/location.
